# Writes MainWindow.xaml.cs directly to avoid encoding issues
$path = "C:\Users\Gavril\PaperlessDesktop\MainWindow.xaml.cs"
$lines = @(
'using PaperlessDesktop.Dialogs;',
'using PaperlessDesktop.Services;',
'using PaperlessDesktop.ViewModels;',
'using PaperlessDesktop.Interop;',
'using PaperlessDesktop.Shared;',
'using System.Runtime.InteropServices;',
'using Microsoft.UI;',
'',
'namespace PaperlessDesktop;',
'',
'public sealed partial class MainWindow : Window',
'{',
'    public MainViewModel ViewModel { get; }',
'',
'    public MainWindow()',
'    {',
'        InitializeComponent();',
'        ViewModel = App.Services.GetRequiredService<MainViewModel>();',
'        ExtendsContentIntoTitleBar = true;',
'        FileListView.ItemsSource = ViewModel.Files;',
'        ViewModel.PropertyChanged += (_, e) =>',
'        {',
'            if (e.PropertyName == nameof(ViewModel.StatusText))',
'                StatusBlock.Text = ViewModel.StatusText;',
'            if (e.PropertyName == nameof(ViewModel.FileCountText))',
'                FileCountBlock.Text = ViewModel.FileCountText;',
'        };',
'        ViewModel.Files.CollectionChanged += (_, _) => RefreshButtonStates();',
'        UpdateLicenseBadge();',
'        RefreshButtonStates();',
'    }',
'',
'    // License badge',
'    private void UpdateLicenseBadge()',
'    {',
'        LicenseStatusBlock.Text = ViewModel.License.LicenseStatusText;',
'        if (ViewModel.License.IsActivated)',
'        {',
'            LicenseBadge.Background = new SolidColorBrush(Color.FromArgb(255, 16, 124, 16));',
'            LicenseStatusBlock.Foreground = new SolidColorBrush(Colors.White);',
'            ActivateBtn.Visibility = Visibility.Collapsed;',
'        }',
'        else if (ViewModel.License.TrialDaysLeft > 0)',
'        {',
'            LicenseBadge.Background = new SolidColorBrush(Color.FromArgb(30, 200, 146, 42));',
'            LicenseStatusBlock.Foreground = new SolidColorBrush(Color.FromArgb(255, 150, 90, 0));',
'        }',
'        else',
'        {',
'            LicenseBadge.Background = new SolidColorBrush(Color.FromArgb(30, 196, 43, 28));',
'            LicenseStatusBlock.Foreground = new SolidColorBrush(Color.FromArgb(255, 196, 43, 28));',
'        }',
'    }',
'',
'    // Button state management',
'    private void RefreshButtonStates()',
'    {',
'        var sel       = FileListView.SelectedItems.Cast<FileItemViewModel>().ToList();',
'        var selPdfs   = sel.Where(f => IsPdf(f.FilePath)).ToList();',
'        var selImages = sel.Where(f => IsImage(f.FilePath)).ToList();',
'        var allPdfs   = ViewModel.Files.Where(f => IsPdf(f.FilePath)).ToList();',
'        bool hasPdfs    = allPdfs.Count > 0;',
'        bool oneSelPdf  = selPdfs.Count == 1;',
'        bool manySelPdf = selPdfs.Count >= 2;',
'        bool anySelImg  = selImages.Count >= 1;',
'        bool anySel     = sel.Count >= 1;',
'',
'        RemoveBtn.IsEnabled   = anySel;',
'        ClearBtn.IsEnabled    = ViewModel.Files.Count > 0;',
'        MoveUpBtn.IsEnabled   = anySel && sel.Count == 1 && ViewModel.Files.IndexOf(sel[0]) > 0;',
'        MoveDownBtn.IsEnabled = anySel && sel.Count == 1 && ViewModel.Files.IndexOf(sel[0]) < ViewModel.Files.Count - 1;',
'        EmptyStatePanel.Visibility = ViewModel.Files.Count == 0 ? Visibility.Visible : Visibility.Collapsed;',
'',
'        BtnMerge.IsEnabled       = manySelPdf;',
'        BtnRemovePages.IsEnabled = oneSelPdf;',
'        BtnRotate.IsEnabled      = oneSelPdf;',
'        BtnInsert.IsEnabled      = oneSelPdf;',
'        BtnPassword.IsEnabled    = oneSelPdf;',
'        BtnUnlock.IsEnabled      = oneSelPdf;',
'        BtnMetadata.IsEnabled    = oneSelPdf;',
'',
'        BtnOcr.IsEnabled        = oneSelPdf;',
'        BtnToDocx.IsEnabled     = oneSelPdf;',
'        BtnToImages.IsEnabled   = oneSelPdf;',
'        BtnFromImages.IsEnabled = anySelImg;',
'        BtnCompress.IsEnabled   = oneSelPdf;',
'        BtnSplit.IsEnabled      = oneSelPdf;',
'',
'        BtnBatchCompress.IsEnabled  = hasPdfs;',
'        BtnBatchOcr.IsEnabled       = hasPdfs;',
'        BtnBatchRemove.IsEnabled    = hasPdfs;',
'        BtnBatchRotate.IsEnabled    = hasPdfs;',
'        BtnBatchToImages.IsEnabled  = hasPdfs;',
'        BtnExportReport.IsEnabled   = ViewModel.LastBatchResult is not null;',
'',
'        SelectionCountBlock.Text = sel.Count > 0 ? $"{sel.Count} selected" : "";',
'    }',
'',
'    private static bool IsPdf(string path) =>',
'        path.EndsWith(".pdf", StringComparison.OrdinalIgnoreCase);',
'',
'    private static bool IsImage(string path)',
'    {',
'        var ext = Path.GetExtension(path).ToLowerInvariant();',
'        return ext is ".png" or ".jpg" or ".jpeg" or ".bmp" or ".tiff" or ".webp";',
'    }',
'',
'    // File list events',
'    private async void AddBtn_Click(object s, RoutedEventArgs e)',
'    {',
'        try',
'        {',
'            var hwnd = WindowNative.GetWindowHandle(this);',
'            var picker = new FileOpenPicker();',
'            InitializeWithWindow.Initialize(picker, hwnd);',
'            foreach (var ext in new[] { ".pdf", ".png", ".jpg", ".jpeg", ".docx", ".csv", ".xlsx" })',
'                picker.FileTypeFilter.Add(ext);',
'            picker.ViewMode = PickerViewMode.List;',
'            var files = await picker.PickMultipleFilesAsync();',
'            if (files?.Count > 0) ViewModel.AddFiles(files.Select(f => f.Path));',
'        }',
'        catch (COMException comEx) when (comEx.HResult == unchecked((int)0x80070578))',
'        {',
'            await Err("File Picker Error", "Could not open file picker. Try restarting the app.");',
'        }',
'        catch (Exception ex)',
'        {',
'            await Err("Error", $"Failed to open file picker: {ex.Message}");',
'        }',
'    }',
'',
'    private void RemoveBtn_Click(object s, RoutedEventArgs e)',
'    {',
'        foreach (var item in FileListView.SelectedItems.Cast<FileItemViewModel>().ToList())',
'            ViewModel.RemoveFile(item);',
'    }',
'',
'    private async void ClearBtn_Click(object s, RoutedEventArgs e)',
'    {',
'        var dlg = new ContentDialog {',
'            Title = "Clear list", Content = "Remove all files from the list?",',
'            PrimaryButtonText = "Yes", CloseButtonText = "No", XamlRoot = Content.XamlRoot',
'        };',
'        if (await dlg.ShowAsync() == ContentDialogResult.Primary) ViewModel.ClearFiles();',
'    }',
'',
'    private void MoveUpBtn_Click(object s, RoutedEventArgs e)',
'    { if (FileListView.SelectedItem is FileItemViewModel item) { ViewModel.MoveUp(item); RefreshButtonStates(); } }',
'',
'    private void MoveDownBtn_Click(object s, RoutedEventArgs e)',
'    { if (FileListView.SelectedItem is FileItemViewModel item) { ViewModel.MoveDown(item); RefreshButtonStates(); } }',
'',
'    private void FileListView_SelectionChanged(object s, SelectionChangedEventArgs e)',
'    {',
'        RefreshButtonStates();',
'        var sel = FileListView.SelectedItems.Cast<FileItemViewModel>().ToList();',
'        if (sel.Count == 1 && IsPdf(sel[0].FilePath)) Preview.LoadPdf(sel[0].FilePath);',
'        else if (sel.Count == 0) Preview.Clear();',
'    }',
'',
'    private void FileListView_DragOver(object s, DragEventArgs e)',
'        => e.AcceptedOperation = Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;',
'',
'    private async void FileListView_Drop(object s, DragEventArgs e)',
'    {',
'        if (e.DataView.Contains(Windows.ApplicationModel.DataTransfer.StandardDataFormats.StorageItems))',
'        {',
'            var items = await e.DataView.GetStorageItemsAsync();',
'            ViewModel.AddFiles(items.Select(i => i.Path));',
'        }',
'    }',
'',
'    // PDF Actions',
'    private async void MergePdfs_Click(object s, RoutedEventArgs e)',
'    {',
'        var sel = ViewModel.SelectedPdfs.ToList();',
'        if (sel.Count < 2) { await Info("Merge PDFs", "Select at least 2 PDF files."); return; }',
'        var out_ = await SaveFile("merged.pdf", ".pdf"); if (out_ is null) return;',
'        await Run("Merging PDFs...", async (_, _) => {',
'            App.Services.GetRequiredService<PdfCoreService>().MergePdfs(sel.Select(f => f.FilePath), out_);',
'            await Info("Merge Complete", $"Merged {sel.Count} files.\n\n{out_}");',
'        });',
'    }',
'',
'    private async void RemovePages_Click(object s, RoutedEventArgs e)',
'    {',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var spec = await Ask("Remove Pages", "Pages to remove (e.g. 1,3-5,7):"); if (spec is null) return;',
'        var out_ = await SaveFile($"{Path.GetFileNameWithoutExtension(sel.FilePath)}_pages_removed.pdf", ".pdf"); if (out_ is null) return;',
'        await Run("Removing pages...", async (_, _) => {',
'            var res = App.Services.GetRequiredService<PdfCoreService>().RemovePages(sel.FilePath, out_, spec);',
'            await Info("Done", $"Removed {res.RemovedCount} page(s).\n\n{out_}");',
'        });',
'    }',
'',
'    private async void RotatePages_Click(object s, RoutedEventArgs e)',
'    {',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var spec  = await Ask("Rotate Pages", "Pages to rotate (e.g. 1,3-5 or all):", "all"); if (spec is null) return;',
'        var angle = await AskInt("Rotation Angle", "Degrees (90 / 180 / 270):", 90); if (angle is null) return;',
'        var out_  = await SaveFile($"{Path.GetFileNameWithoutExtension(sel.FilePath)}_rotated.pdf", ".pdf"); if (out_ is null) return;',
'        await Run("Rotating pages...", async (_, _) => {',
'            App.Services.GetRequiredService<PdfCoreService>().RotatePages(sel.FilePath, out_, spec, angle.Value);',
'            await Info("Done", $"Pages rotated {angle} degrees.\n\n{out_}");',
'        });',
'    }',
'',
'    private async void InsertPages_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Insert Pages")) return;',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var src   = await OpenFile(".pdf"); if (src is null) return;',
'        var after = await AskInt("Insert Position", "Insert after page number (0 = beginning):", 0); if (after is null) return;',
'        var out_  = await SaveFile($"{Path.GetFileNameWithoutExtension(sel.FilePath)}_inserted.pdf", ".pdf"); if (out_ is null) return;',
'        App.Services.GetRequiredService<PdfCoreService>().InsertPages(sel.FilePath, src, after.Value, out_);',
'        await Info("Done", $"Pages inserted.\n\n{out_}");',
'    }',
'',
'    private async void PasswordProtect_Click(object s, RoutedEventArgs e)',
'    { if (!RequirePro("Password Protect")) return; await Info("Coming Soon", "Requires iText7. See roadmap Step 6."); }',
'',
'    private async void UnlockPdf_Click(object s, RoutedEventArgs e)',
'    { if (!RequirePro("Unlock PDF")) return; await Info("Coming Soon", "Requires iText7. See roadmap Step 6."); }',
'',
'    private async void EditMetadata_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Edit Metadata")) return;',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var title   = await Ask("Title",    "Document title:",   ""); if (title is null) return;',
'        var author  = await Ask("Author",   "Author name:",      ""); if (author is null) return;',
'        var subject = await Ask("Subject",  "Subject:",          ""); if (subject is null) return;',
'        var keys    = await Ask("Keywords", "Keywords:",         ""); if (keys is null) return;',
'        var out_    = await SaveFile($"{Path.GetFileNameWithoutExtension(sel.FilePath)}_meta.pdf", ".pdf"); if (out_ is null) return;',
'        App.Services.GetRequiredService<PdfCoreService>().EditMetadata(sel.FilePath, out_, title, author, subject, keys);',
'        await Info("Done", $"Metadata updated.\n\n{out_}");',
'    }',
'',
'    // Pro Actions',
'    private async void OcrPdf_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("OCR PDF")) return;',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var out_ = await SaveFile($"{Path.GetFileNameWithoutExtension(sel.FilePath)}_ocr.pdf", ".pdf"); if (out_ is null) return;',
'        await Run("Running OCR...", async (prog, ct) => {',
'            var res = await App.Services.GetRequiredService<PdfConvertService>().OcrPdfAsync(sel.FilePath, out_, progress: prog, ct: ct);',
'            await Info("OCR Complete", $"{res.PagesProcessed} page(s) processed.\n\n{out_}");',
'        });',
'    }',
'',
'    private async void PdfToDocx_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("PDF to Word")) return;',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var out_ = await SaveFile($"{Path.GetFileNameWithoutExtension(sel.FilePath)}.docx", ".docx"); if (out_ is null) return;',
'        await Run("Converting to Word...", async (_, ct) => {',
'            await App.Services.GetRequiredService<PdfConvertService>().PdfToDocxAsync(sel.FilePath, out_, ct: ct);',
'            await Info("Done", $"Saved as Word document.\n\n{out_}");',
'        });',
'    }',
'',
'    private async void PdfToImages_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("PDF to Images")) return;',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var outDir = await PickFolder(); if (outDir is null) return;',
'        await Run("Exporting pages as images...", async (prog, ct) => {',
'            var imgs = await App.Services.GetRequiredService<PdfConvertService>().PdfToImagesAsync(sel.FilePath, outDir, progress: prog, ct: ct);',
'            await Info("Done", $"{imgs.Count} image(s) saved to:\n{outDir}");',
'        });',
'    }',
'',
'    private async void ImagesToPdf_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Images to PDF")) return;',
'        var images = ViewModel.SelectedImages.ToList();',
'        if (images.Count == 0) { await Info("Images to PDF", "Select at least one image."); return; }',
'        var out_ = await SaveFile("images.pdf", ".pdf"); if (out_ is null) return;',
'        await Run($"Creating PDF from {images.Count} image(s)...", async (prog, ct) => {',
'            await App.Services.GetRequiredService<PdfConvertService>().ImagesToPdfAsync(images.Select(f => f.FilePath), out_, progress: prog, ct: ct);',
'            await Info("Done", $"PDF created from {images.Count} image(s).\n\n{out_}");',
'        });',
'    }',
'',
'    private async void CompressPdf_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Compress PDF")) return;',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var quality = await AskQuality(); if (quality is null) return;',
'        var out_ = await SaveFile($"{Path.GetFileNameWithoutExtension(sel.FilePath)}_compressed.pdf", ".pdf"); if (out_ is null) return;',
'        await Run("Compressing PDF...", async (_, _) => {',
'            var res = App.Services.GetRequiredService<PdfCoreService>().CompressPdf(sel.FilePath, out_, quality);',
'            var msg = res.KeptOriginal',
'                ? $"File was already optimal. Size: {FormatBytes(res.OutputSize)}"',
'                : $"{FormatBytes(res.OriginalSize)} -> {FormatBytes(res.OutputSize)} ({res.SavingsPct:F1}% smaller)";',
'            await Info("Compression Complete", msg + $"\n\n{out_}");',
'        });',
'    }',
'',
'    private async void SplitPdf_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Split PDF")) return;',
'        var sel = ViewModel.SelectedPdfs.FirstOrDefault(); if (sel is null) return;',
'        var outDir = await PickFolder(); if (outDir is null) return;',
'        var byN = await YesNo("Split Method", "Yes = split every N pages\nNo = split by custom ranges");',
'        SplitResult res;',
'        if (byN) {',
'            var n = await AskInt("Pages per chunk", "Split every N pages:", 2); if (n is null) return;',
'            res = App.Services.GetRequiredService<PdfCoreService>().SplitEveryN(sel.FilePath, outDir, n.Value);',
'        } else {',
'            var spec = await Ask("Page Ranges", "Enter ranges (e.g. 1-3, 5, 7-9):"); if (spec is null) return;',
'            res = App.Services.GetRequiredService<PdfCoreService>().SplitByRanges(sel.FilePath, outDir, spec);',
'        }',
'        await Info("Split Complete", $"Created {res.OutputFiles.Count} file(s) in:\n{outDir}");',
'    }',
'',
'    // Batch Actions',
'    private async void BatchCompress_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Batch Compress")) return;',
'        var quality = await AskQuality(); if (quality is null) return;',
'        var files   = ViewModel.AllOrSelected().Select(f => f.FilePath).ToList();',
'        var outDir  = await PickFolder(); if (outDir is null) return;',
'        await Run($"Compressing {files.Count} file(s)...", async (prog, ct) => {',
'            var res = await App.Services.GetRequiredService<BatchService>().BatchCompressAsync(files, outDir, quality, prog, ct);',
'            ViewModel.LastBatchResult = res; BtnExportReport.IsEnabled = true;',
'            await Info("Batch Complete", res.Summary());',
'        });',
'    }',
'',
'    private async void BatchOcr_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Batch OCR")) return;',
'        var files  = ViewModel.AllOrSelected().Select(f => f.FilePath).ToList();',
'        var outDir = await PickFolder(); if (outDir is null) return;',
'        await Run($"OCR processing {files.Count} file(s)...", async (prog, ct) => {',
'            var res = await App.Services.GetRequiredService<BatchService>().BatchOcrAsync(files, outDir, prog: prog, ct: ct);',
'            ViewModel.LastBatchResult = res; BtnExportReport.IsEnabled = true;',
'            await Info("Batch Complete", res.Summary());',
'        });',
'    }',
'',
'    private async void BatchRemove_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Batch Remove Pages")) return;',
'        var spec   = await Ask("Remove Pages", "Pages to remove from ALL files (e.g. 1,3-5):"); if (spec is null) return;',
'        var files  = ViewModel.AllOrSelected().Select(f => f.FilePath).ToList();',
'        var outDir = await PickFolder(); if (outDir is null) return;',
'        await Run($"Removing pages from {files.Count} file(s)...", async (prog, ct) => {',
'            var res = await App.Services.GetRequiredService<BatchService>().BatchRemovePagesAsync(files, outDir, spec, prog, ct);',
'            ViewModel.LastBatchResult = res; BtnExportReport.IsEnabled = true;',
'            await Info("Batch Complete", res.Summary());',
'        });',
'    }',
'',
'    private async void BatchRotate_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Batch Rotate")) return;',
'        var spec   = await Ask("Pages", "Pages to rotate (all or e.g. 1,3-5):", "all"); if (spec is null) return;',
'        var angle  = await AskInt("Angle", "Rotation angle (90/180/270):", 90); if (angle is null) return;',
'        var files  = ViewModel.AllOrSelected().Select(f => f.FilePath).ToList();',
'        var outDir = await PickFolder(); if (outDir is null) return;',
'        await Run($"Rotating {files.Count} file(s)...", async (prog, ct) => {',
'            var res = await App.Services.GetRequiredService<BatchService>().BatchRotateAsync(files, outDir, spec, angle.Value, prog, ct);',
'            ViewModel.LastBatchResult = res; BtnExportReport.IsEnabled = true;',
'            await Info("Batch Complete", res.Summary());',
'        });',
'    }',
'',
'    private async void BatchPdfImages_Click(object s, RoutedEventArgs e)',
'    {',
'        if (!RequirePro("Batch PDF to Images")) return;',
'        var files  = ViewModel.AllOrSelected().Select(f => f.FilePath).ToList();',
'        var outDir = await PickFolder(); if (outDir is null) return;',
'        await Run($"Exporting images from {files.Count} file(s)...", async (prog, ct) => {',
'            var res = await App.Services.GetRequiredService<BatchService>().BatchPdfToImagesAsync(files, outDir, prog: prog, ct: ct);',
'            ViewModel.LastBatchResult = res; BtnExportReport.IsEnabled = true;',
'            await Info("Batch Complete", res.Summary());',
'        });',
'    }',
'',
'    private async void ExportReport_Click(object s, RoutedEventArgs e)',
'    {',
'        if (ViewModel.LastBatchResult is null) { await Info("No Report", "Run a batch operation first."); return; }',
'        var out_ = await SaveFile("batch_report.csv", ".csv"); if (out_ is null) return;',
'        BatchService.ExportReport(ViewModel.LastBatchResult, out_);',
'        await Info("Report Saved", $"CSV report saved to:\n{out_}");',
'    }',
'',
'    // Files tab',
'    private async void ImageEditor_Click(object s, RoutedEventArgs e)      => await Info("Image Editor",  "Coming soon. See roadmap Step 3.");',
'    private async void DocxFindReplace_Click(object s, RoutedEventArgs e)  => await Info("Find & Replace","Coming soon. See roadmap Step 4.");',
'    private async void DocxMerge_Click(object s, RoutedEventArgs e)        => await Info("Merge DOCX",    "Coming soon. See roadmap Step 4.");',
'    private async void CsvViewer_Click(object s, RoutedEventArgs e)        => await Info("Table Editor",  "Coming soon. See roadmap Step 5.");',
'',
'    // Activate Pro',
'    private async void ActivateBtn_Click(object s, RoutedEventArgs e)',
'    {',
'        var dlg = new ActivationDialog(Content.XamlRoot);',
'        if (await dlg.ShowAsync() == ContentDialogResult.Primary)',
'        {',
'            if (ViewModel.License.Activate(dlg.UserId, dlg.LicenseKey))',
'            {',
'                UpdateLicenseBadge();',
'                await Info("Pro Activated!", "All Pro features are now unlocked.");',
'            }',
'            else await Err("Invalid Key", "That license key is not valid. Please check and try again.");',
'        }',
'    }',
'',
'    private bool RequirePro(string feature)',
'    {',
'        if (ViewModel.License.IsPro) return true;',
'        _ = Info("Pro Feature Required",',
'            $"{feature} is only available in the Pro version.\n\nClick Activate Pro to unlock all features.");',
'        return false;',
'    }',
'',
'    // Progress runner',
'    private async Task Run(string title, Func<IProgress<(int, int, string)>, CancellationToken, Task> work)',
'    {',
'        var dlg = new ProgressDialog(Content.XamlRoot, title); _ = dlg.ShowAsync();',
'        try {',
'            var prog = new Progress<(int d, int t, string n)>(x => dlg.Update(x.d, x.t, x.n));',
'            await work(prog, dlg.CancellationToken);',
'        }',
'        catch (OperationCanceledException) { }',
'        catch (Exception ex) { await Err("Error", ex.Message); }',
'        finally { dlg.Hide(); }',
'    }',
'',
'    // Pickers',
'    private async Task<string?> SaveFile(string suggested, string ext)',
'    {',
'        var p = new FileSavePicker();',
'        InitializeWithWindow.Initialize(p, WindowNative.GetWindowHandle(this));',
'        p.SuggestedFileName = suggested;',
'        p.FileTypeChoices.Add(ext.TrimStart('"'"'.'"'"').ToUpperInvariant(), new List<string> { ext });',
'        return (await p.PickSaveFileAsync())?.Path;',
'    }',
'',
'    private async Task<string?> OpenFile(string ext)',
'    {',
'        var p = new FileOpenPicker();',
'        InitializeWithWindow.Initialize(p, WindowNative.GetWindowHandle(this));',
'        p.FileTypeFilter.Add(ext);',
'        return (await p.PickSingleFileAsync())?.Path;',
'    }',
'',
'    private async Task<string?> PickFolder()',
'    {',
'        var p = new FolderPicker();',
'        InitializeWithWindow.Initialize(p, WindowNative.GetWindowHandle(this));',
'        p.FileTypeFilter.Add("*");',
'        return (await p.PickSingleFolderAsync())?.Path;',
'    }',
'',
'    // Dialog helpers',
'    private Task Info(string title, string msg) =>',
'        new ContentDialog { Title = title, Content = msg, CloseButtonText = "OK", XamlRoot = Content.XamlRoot }.ShowAsync().AsTask();',
'',
'    private Task Err(string title, string msg) =>',
'        new ContentDialog { Title = title, Content = msg, CloseButtonText = "OK", XamlRoot = Content.XamlRoot }.ShowAsync().AsTask();',
'',
'    private async Task<string?> Ask(string title, string prompt, string def = "")',
'    {',
'        var tb  = new TextBox { Text = def, PlaceholderText = prompt };',
'        var dlg = new ContentDialog {',
'            Title = title,',
'            Content = new StackPanel { Spacing = 8, Children = {',
'                new TextBlock { Text = prompt, TextWrapping = TextWrapping.Wrap, Opacity = 0.8 }, tb } },',
'            PrimaryButtonText = "OK", CloseButtonText = "Cancel", XamlRoot = Content.XamlRoot',
'        };',
'        return await dlg.ShowAsync() == ContentDialogResult.Primary ? tb.Text.Trim() : null;',
'    }',
'',
'    private async Task<int?> AskInt(string title, string prompt, int def)',
'    {',
'        var nb = new NumberBox { Value = def, SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Inline, Minimum = 0 };',
'        var dlg = new ContentDialog {',
'            Title = title,',
'            Content = new StackPanel { Spacing = 8, Children = {',
'                new TextBlock { Text = prompt, TextWrapping = TextWrapping.Wrap, Opacity = 0.8 }, nb } },',
'            PrimaryButtonText = "OK", CloseButtonText = "Cancel", XamlRoot = Content.XamlRoot',
'        };',
'        return await dlg.ShowAsync() == ContentDialogResult.Primary ? (int)nb.Value : null;',
'    }',
'',
'    private async Task<string?> AskQuality()',
'    {',
'        var cb = new ComboBox { ItemsSource = new[] { "screen", "ebook", "printer", "prepress" },',
'            SelectedItem = "ebook", HorizontalAlignment = HorizontalAlignment.Stretch };',
'        var info = new TextBlock {',
'            Text = "screen = smallest file\nebook = balanced (recommended)\nprinter = high quality\nprepress = professional print",',
'            FontSize = 12, Opacity = 0.7, Margin = new Thickness(0, 0, 0, 8) };',
'        var dlg = new ContentDialog {',
'            Title = "Compression Quality",',
'            Content = new StackPanel { Spacing = 6, Children = { info, cb } },',
'            PrimaryButtonText = "Compress", CloseButtonText = "Cancel", XamlRoot = Content.XamlRoot',
'        };',
'        return await dlg.ShowAsync() == ContentDialogResult.Primary ? cb.SelectedItem as string : null;',
'    }',
'',
'    private async Task<bool> YesNo(string title, string prompt)',
'    {',
'        var dlg = new ContentDialog {',
'            Title = title,',
'            Content = new TextBlock { Text = prompt, TextWrapping = TextWrapping.Wrap },',
'            PrimaryButtonText = "Yes", SecondaryButtonText = "No", XamlRoot = Content.XamlRoot',
'        };',
'        return await dlg.ShowAsync() == ContentDialogResult.Primary;',
'    }',
'',
'    private static string FormatBytes(long n)',
'    {',
'        foreach (var u in new[] { "B", "KB", "MB", "GB" }) { if (n < 1024) return $"{n:F1} {u}"; n /= 1024; }',
'        return $"{n:F1} TB";',
'    }',
'}'
)

[System.IO.File]::WriteAllLines($path, $lines, [System.Text.Encoding]::UTF8)
Write-Host "Written: $path" -ForegroundColor Green
